baseURL: https://signalflags.org/
languageCode: en-gb
title: Signal Flags
publishDir: ../signal-flags.github.io/docs
# relativeURLS: true
theme: sf-theme
markup:
  highlight:
    style: github
    noClasses: false
  goldmark:
    parser:
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true

params:
  showWordCount: false
  showDate: false
  description: >-
    Flags and pennants from the International Code of Signals and other RRS
    (sailing) flags including free SVG vector images to download.
  themeColor: '#224c73'
  highlightTheme: monokai

  seo:
    siteName: signalflags.org
    baseURL: https://signalflags.org/

    # Fallback image url if the page doesn't have a featured image.
    # image: https://example.com/image.png.
    # imageAlt: Alt text for the image.

    # Type of display for Twitter.
    twitterCard: summary_image

    # App Id for Facebook analytics.
    # fbAppId:

    # Twitter username for Twitter analytics.
    twitterSite: '@signalflags_org'

module:
  mounts:
    source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
    target: assets/js/bootstrap.bundle.min.js

menus:
  nav:
    - name: Flags
      url: /flags/
      weight: 100

    - name: Download
      url: /download/
      weight: 200

    - name: About
      url: /about/
      weight: 400

    - name: Help
      url: /help/
      weight: 500
